### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by eagui041** [uoPath/bug-report#3]
### What happened?

Sometimes, and I'm sorry this only happens sometimes, the course description hides my ability to see where I am placing my course block.

![Capture](https://github.com/uoPath/bug-report/assets/145598022/1b125de2-baf2-4652-8c13-dff84e05c619)

### What did you expect to happen?

The expected behaviour would be to hide the description if the block is being moved.

### What were you doing before the issue occurred?

1. Go to 'any course block'
2. Hover on the block to read the description.
3. Click on the course block to move it.
4. The target area is obstructed by description.

### Did you see any error messages?

No.

### Operating System

Windows 10

### Browser

Chrome Version 117.0.5938.92

**Comment by Icecovery** [comment]
Fixed.
