### ISSUE TITLE
[Bug]: Tutorial every time password is reset

### ISSUE THREAD

**Issue by nate12864** [uoPath/bug-report#4]
### What happened?

I forgot my password a couple times and every time I reset it I would get the tutorial on my first time connecting to my account.

### What did you expect to happen?

no tutorial

### What were you doing before the issue occurred?

1. Go to forgot my password
2. click on link to reset the password sent by email
3. connect with new password

### Did you see any error messages?

no

### Operating System

Windows 11

### Browser

Chrome

**Comment by Icecovery** [comment]
Fixed.
